# Generated by Django 3.0.6 on 2021-04-13 17:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='About',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('text', models.TextField(blank=True, null=True)),
                ('ph1', models.IntegerField(blank=True, null=True)),
                ('ph2', models.IntegerField(blank=True, null=True)),
            ],
        ),
    ]
